server:
  port: 8080
  servlet:
    context-path: /note
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.7:3306/hq_note?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.0.7
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: false
      logic-delete-value: true
      logic-delete-field: deleted
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-enums-package: com.hq.note.enums
logging:
  level:
    com.hq.note.mapper: debug
token:
  key: 123456
springfox:
  documentation:
    enabled: true
swagger:
  title: HQ笔记
  description: 一个简单的笔记项目
  contact:
    name: HQ
    email: 1228234037@qq.com
  exclude-path: /error
ali:
  oss:
    bucket: ""
    endpoint: ""
    accessKeyId: ""
    accessKeySecret: ""
    imageDomainName: ""